version: "2.2"
services:
  app:
    container_name: vue-evernote-api
    build: .
    expose:
      - "8080"
    env_file:
      - ./config/dev.env
    depends_on:
      - mongo
    ports:
      - "8080:8080"
  mongo:
    image: mongo
    container_name: vue-evernote-db
    ports:
      - "27017:27017"
